# Generated by Django 5.0.8 on 2025-07-09 11:15

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('pays_naissance', models.CharField(max_length=100)),
                ('nationalite1', models.CharField(max_length=50)),
                ('nationalite2', models.CharField(blank=True, max_length=50, null=True)),
                ('etat_civil', models.CharField(max_length=50)),
                ('nom_conjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('pays_residence', models.CharField(max_length=100)),
                ('agence', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('cnioupassport', models.FileField(upload_to='documents/cni_passport/')),
                ('relevecompte', models.FileField(upload_to='documents/releve_compte/')),
                ('preuveadresse', models.FileField(upload_to='documents/preuve_adresse/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('devise', models.CharField(default='EUR', max_length=10)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
