# Generated by Django 5.0.8 on 2025-07-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_adresse_alter_user_agence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
