# Generated by Django 5.0.8 on 2025-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='nom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
