# Generated by Django 5.0.8 on 2025-07-14 22:29

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compte_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='core.assistant'),
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('banque', models.CharField(max_length=100)),
                ('guichet', models.CharField(max_length=50)),
                ('rib', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=50)),
                ('bic', models.CharField(max_length=50)),
                ('domiciliation', models.TextField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('virement', 'Virement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nom_beneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('banque_beneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('bic', models.CharField(blank=True, max_length=15, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nom_beneficiaire', models.CharField(max_length=255)),
                ('banque_beneficiaire', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(max_length=11)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_virement', models.DateTimeField(auto_now_add=True)),
                ('compte_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_emis', to='core.compte')),
            ],
        ),
    ]
