# Generated by Django 5.0.8 on 2025-07-23 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assistant_user_assistant_depot_transaction_virement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='banque_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='nom_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preuveadresse',
        ),
        migrations.CreateModel(
            name='ProofOfAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/preuve_adresse/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs_of_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='preuveadresse',
            field=models.ManyToManyField(blank=True, null=True, related_name='usersproofs', to='core.proofofaddress'),
        ),
    ]
