# Generated by Django 5.0.8 on 2025-07-23 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transaction_banque_beneficiaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_type', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT_SOL', 'USDT (Solana)'), ('USDT_ETH', 'USDT (Ethereum)'), ('USDT_BSC', 'USDT (BSC)')], max_length=10, verbose_name='Type de cryptomonnaie')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(1e-08)], verbose_name='Montant déposé')),
                ('btc_address', models.CharField(blank=True, max_length=42, null=True, verbose_name='Adresse Bitcoin')),
                ('usdt_sol_address', models.CharField(blank=True, max_length=44, null=True, verbose_name='Adresse USDT (Solana)')),
                ('usdt_eth_address', models.CharField(blank=True, max_length=42, null=True, verbose_name='Adresse USDT (Ethereum)')),
                ('usdt_bsc_address', models.CharField(blank=True, max_length=42, null=True, verbose_name='Adresse USDT (BSC)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots_crypto', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Dépôt Cryptomonnaie',
                'verbose_name_plural': 'Dépôts Cryptomonnaie',
                'ordering': ['-created_at'],
            },
        ),
    ]
