# Generated by Django 5.0.8 on 2025-07-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_depotcrypto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preuveadresse',
        ),
        migrations.DeleteModel(
            name='ProofOfAddress',
        ),
        migrations.AddField(
            model_name='user',
            name='preuveadresse',
            field=models.FileField(blank=True, null=True, upload_to='documents/preuve_adresse/'),
        ),
    ]
