from django.urls import path
from .views import *

urlpatterns = [
    path('',index, name="index"),
    path('particulier',particulier, name="particulier"),
    # path('tweenz',tweenss, name="tweenz"),
    # path('axxess',axxess, name="axxess"),
    # path('professionnels',professionnel, name="professionnels"),
    # path('private_banking',privatebanking, name="private_banking"),
    path('a_propos',apropos, name="a_propos"),
    path('devenir_client',devenirclient, name="devenir_client"),
    path('register',register, name="register"),
    path('login',login, name="login"),
    path('Mon_compte',dashboard, name="Mon_compte"),
    path('add_compte',add_compte, name="add_compte"),
    path('logout', logout_view, name='logout'),
    path('change_password', change_password, name='change_password'),

    path('depot/<str:compte_id>/',depot_view, name='depot'),
    path('virement/', virement, name='virement'),

    path('outils',apropos, name="outils"),
    path('fonds_durables',apropos, name="fonds_durables"),
    path('notre_reseau_agence',apropos, name="notre_reseau_agence"),
    path('simulation_pret_personnel',apropos, name="simulation_pret_personnel"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('zebra_premium',apropos, name="zebra_premium"),
    path('pret_plus_lease_plus',apropos, name="pret_plus_lease_plus"),
    path('pret_au_logement',apropos, name="pret_au_logement"),
    path('s_pension',apropos, name="s_pension"),
    path('jeunes_actifs',apropos, name="jeunes_actifs"),
    path('etudiants',apropos, name="etudiants"),
    path('pret_etudiant',apropos, name="pret_etudiant"),
    path('parents',apropos, name="parents"),
    path('s_invest',apropos, name="s_invest"),
    path('your_bank_in_luxembourg',apropos, name="your_bank_in_luxembourg"),
    path('snet',apropos, name="snet"),
    path('sustainability',apropos, name="sustainability"),
    path('blog_accueil',apropos, name="blog_accueil"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),
    path('simulation_logement',apropos, name="simulation_logement"),

]